from saltstack/centos-7-minimal

WORKDIR "/srv"
RUN yum install -y python-pip
COPY ./requirements /tmp/requirements
RUN pip install -r /tmp/requirements/dev.txt

RUN pip install -r /tmp/requirements.txt
COPY ./templates/etc/minion.image /etc/salt/minion
RUN echo "master: master" >> /etc/salt/minion
CMD salt-minion -l debug
