from saltstack/centos-7-minimal

WORKDIR "/srv"
RUN yum install -y python-pip
COPY ./requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt
COPY ./templates/etc/minion.vagrant /etc/salt/minion
CMD tail -f /dev/null
