from saltstack/centos-7-minimal

WORKDIR "/srv"
RUN yum install -y python-pip
COPY ./requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt
COPY ./salt/etc/minion.image /etc/salt/minion
RUN echo "master: master" >> /etc/salt/minion
CMD salt-minion -l debug
