from saltstack/centos-7-minimal

COPY ./salt/etc/minion.vagrant /etc/salt/minion
COPY ./requirements.txt /tmp/requirements.txt

WORKDIR "/srv"
RUN yum install -y python-pip
RUN pip install -r /tmp/requirements.txt
CMD tail -f /dev/null
