#! /usr/bin/env python
import os
import sys
import subprocess

PYTHON_VERSION = "2.7.5"
PIP_VERSION = "9.0.1"

print "Checking python..."
if ".".join(map(lambda s: str(s), sys.version_info[:3])) != PYTHON_VERSION:
    raise Exception("setup requires python 2.7.5")

print "Checking pip..."
try:
    import pip
except Exception as e:
    raise Exception("setup requires pip version 9.0.1")
else:
    if pip.__version__ != PIP_VERSION:
        raise Exception("setup requires pip version 9.0.1")

print "Installing requirements..."
cmd = "pip install -r %s/../requirements.txt" % (os.path.dirname(os.path.realpath(__file__)))
subprocess.check_call(cmd.split())

print "Setup complete!"
